"""
Generate manifest.json — single source of truth for all site numbers.

Reads platforms.json and ip_bulk_results.json, computes every metric
displayed on the site, and writes manifest.json. The site reads this
file instead of computing stats inline or hardcoding numbers.

Usage:
    python scripts/generate_manifest.py
"""

import json
from pathlib import Path

PROJECT = Path(__file__).parent.parent
DATA = PROJECT / "data"
SITE_DATA = PROJECT / "site" / "src" / "data"


def main():
    # Load source data
    with open(SITE_DATA / "platforms.json") as f:
        platforms = json.load(f)

    findings = platforms.get("findings", [])

    # --- Global stats ---
    total = len(findings)
    by_status = {}
    for f in findings:
        s = f["status"]
        by_status[s] = by_status.get(s, 0) + 1

    by_category = {}
    for f in findings:
        c = f["category"]
        if c not in by_category:
            by_category[c] = {"total": 0, "correct": 0, "incorrect": 0, "ambiguous": 0, "blocked": 0, "n/a": 0}
        by_category[c]["total"] += 1
        by_category[c][f["status"]] += 1

    by_method = {}
    for f in findings:
        m = f["method"]
        by_method[m] = by_method.get(m, 0) + 1

    # --- IP geolocation stats ---
    ip_data = platforms.get("ip_results", {})
    ip_by_country = ip_data.get("by_country", {})
    ip_total_lookups = ip_data.get("total_lookups", 0)
    ip_total_ips = ip_data.get("total_ips", 0)
    ip_total_asns = ip_data.get("total_asns", 0)
    ip_total_results = sum(ip_by_country.values()) if ip_by_country else 0

    # --- Per-category breakdowns ---
    def cat_stats(category):
        items = [f for f in findings if f["category"] == category]
        return {
            "total": len(items),
            "correct": sum(1 for f in items if f["status"] == "correct"),
            "incorrect": sum(1 for f in items if f["status"] == "incorrect"),
            "ambiguous": sum(1 for f in items if f["status"] == "ambiguous"),
            "blocked": sum(1 for f in items if f["status"] == "blocked"),
            "n/a": sum(1 for f in items if f["status"] == "n/a"),
        }

    # --- Build manifest ---
    manifest = {
        "_generated": "Auto-generated by pipelines/_shared/generate_manifest.py. Do not edit manually.",

        "global": {
            "total_platforms": total,
            "total_categories": len(by_category),
            "by_status": by_status,
            "by_method": by_method,
        },

        "weather": cat_stats("weather"),
        "map_service": cat_stats("map_service"),
        "ip_geolocation": {
            **cat_stats("ip_geolocation"),
            "total_ips_tested": ip_total_ips,
            "total_asns_tested": ip_total_asns,
            "total_lookups": ip_total_lookups,
            "by_country": ip_by_country,
            "pct_ua": round(ip_by_country.get("UA", 0) / max(ip_total_results, 1) * 100),
            "pct_ru": round(ip_by_country.get("RU", 0) / max(ip_total_results, 1) * 100),
            "pct_other": round(ip_by_country.get("other", 0) / max(ip_total_results, 1) * 100),
        },
        "telecom": cat_stats("telecom"),
        "tech_infrastructure": cat_stats("tech_infrastructure"),
        "data_visualization": cat_stats("data_visualization"),
        "open_source": cat_stats("open_source"),
        "reference": cat_stats("reference"),
        "travel": cat_stats("travel"),
        "search_engine": cat_stats("search_engine"),
        "sports": cat_stats("sports"),

        "methodology": {
            "source_code": by_method.get("source_code", 0),
            "automated_api": by_method.get("automated_api", 0),
            "automated_data": by_method.get("automated_data", 0),
        },

        "by_category": by_category,
    }

    # Write
    out = SITE_DATA / "manifest.json"
    with open(out, "w") as f:
        json.dump(manifest, f, indent=2, ensure_ascii=False)

    print(f"Generated {out}")
    print(f"  Total: {total} platforms across {len(by_category)} categories")
    print(f"  Status: {by_status}")
    print(f"  Methods: {by_method}")


if __name__ == "__main__":
    main()
